/**
 * THIS FILE IS AUTOMATICALLY GENERATED
 * DO NOT EDIT THIS FILE
 */
import * as TX from './ApiTypes.js';
import { BaseCon, HandleRes } from '@grandlinex/base-con';
import IApiCon from './IApiCon.js';

export default class ApiCon extends BaseCon implements IApiCon{
  /* REPLACE_ME */
}
