/**
 * THIS FILE IS AUTOMATICALLY GENERATED
 * DO NOT EDIT THIS FILE
 */
import * as TX from './ApiTypes';
import BaseCon,{ HandleRes } from './BaseCon';
import IApiCon from './IApiCon';

export default class ApiCon extends BaseCon implements IApiCon{
  /* REPLACE_ME */
}
