/**
 * THIS FILE IS AUTOMATICALLY GENERATED
 * DO NOT EDIT THIS FILE
 */
import * as TX from './ApiTypes.js';
import { HandleRes } from './BaseCon.js';
import IApiCon from './IApiCon.js';

export default abstract class CApiCon implements IApiCon{
  /* REPLACE_ME */
}
