/**
 * THIS FILE IS AUTOMATICALLY GENERATED
 * DO NOT EDIT THIS FILE
 */
import * as TX from './ApiTypes';
import { HandleRes } from './BaseCon';
import IApiCon from './IApiCon';

export default abstract class CApiCon implements IApiCon{
  /* REPLACE_ME */
}
