/**
 * THIS FILE IS AUTOMATICALLY GENERATED
 * DO NOT EDIT THIS FILE
 */
import * as TX from './ApiTypes.js';
import { HandleRes } from './BaseCon.js';

export default interface IApiCon {
  /* REPLACE_ME */
}
