/**
 * THIS FILE IS AUTOMATICALLY GENERATED
 * DO NOT EDIT THIS FILE
 */
import * as TX from './ApiTypes';
import { HandleRes } from './BaseCon';

export default interface IApiCon {
  /* REPLACE_ME */
}
